#include <nanobind/nanobind.h>
#include <nanobind/ndarray.h>
#include <nanobind/stl/array.h>
#include <nanobind/stl/function.h>
#include <nanobind/stl/map.h>
#include <nanobind/stl/optional.h>
#include <nanobind/stl/pair.h>
#include <nanobind/stl/shared_ptr.h>
#include <nanobind/stl/string.h>
#include <nanobind/stl/tuple.h>
#include <nanobind/stl/unique_ptr.h>
#include <nanobind/stl/unordered_set.h>
#include <nanobind/stl/vector.h>
#include <nanobind/trampoline.h>

#include <pacer/datatypes/datatypes.hpp>
#include <pacer/geometry/geometry.hpp>
#include <pacer/gps-source/gps-source.hpp>
#include <pacer/laps-display/laps-display.hpp>
#include <pacer/laps/laps.hpp>

namespace nb = nanobind;
using namespace pacer;

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! <litgen_glue_code>  // Autogenerated code

namespace pacer {
// helper type to enable overriding virtual methods in python
class RawGPSSource_trampoline : public RawGPSSource {
public:
  NB_TRAMPOLINE(RawGPSSource, 5);

  uint32_t Seek(double target) override {
    NB_OVERRIDE_PURE_NAME("seek", // function name (python)
                          Seek,   // function name (c++)
                          target  // params
    );
  }
  void Next() override {
    NB_OVERRIDE_PURE_NAME("next", // function name (python)
                          Next    // function name (c++)
    );
  }
  bool IsEnd() override {
    NB_OVERRIDE_PURE_NAME("is_end", // function name (python)
                          IsEnd     // function name (c++)
    );
  }
  std::pair<double, double> CurrentTimeSpan() const override {
    NB_OVERRIDE_PURE_NAME("current_time_span", // function name (python)
                          CurrentTimeSpan      // function name (c++)
    );
  }
  double GetTotalDuration() const override {
    NB_OVERRIDE_PURE_NAME("get_total_duration", // function name (python)
                          GetTotalDuration      // function name (c++)
    );
  }
};
} // namespace pacer

// </litgen_glue_code> // Autogenerated code end
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

void py_init_module_pacer(nb::module_ &m) {
  // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE
  // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! <litgen_pydef> // Autogenerated code
  ////////////////////    <generated_from:datatypes.hpp>    ////////////////////
  auto pyClassGPSSample =
      nb::class_<pacer::GPSSample>(m, "GPSSample", "")
          .def(
              "__init__",
              [](pacer::GPSSample *self, double lat = double(),
                 double lon = double(), double altitude = 0,
                 double full_speed = 0, double ground_speed = 0,
                 int64_t timestamp_ms = 0) {
                new (self) pacer::GPSSample(); // placement new
                auto r_ctor_ = self;
                r_ctor_->lat = lat;
                r_ctor_->lon = lon;
                r_ctor_->altitude = altitude;
                r_ctor_->full_speed = full_speed;
                r_ctor_->ground_speed = ground_speed;
                r_ctor_->timestamp_ms = timestamp_ms;
              },
              nb::arg("lat") = double(), nb::arg("lon") = double(),
              nb::arg("altitude") = 0, nb::arg("full_speed") = 0,
              nb::arg("ground_speed") = 0, nb::arg("timestamp_ms") = 0)
          .def_rw("lat", &pacer::GPSSample::lat, "")
          .def_rw("lon", &pacer::GPSSample::lon, "")
          .def_rw("altitude", &pacer::GPSSample::altitude, "")
          .def_rw("full_speed", &pacer::GPSSample::full_speed, "")
          .def_rw("ground_speed", &pacer::GPSSample::ground_speed, "")
          .def_rw("timestamp_ms", &pacer::GPSSample::timestamp_ms, "");

  auto pyClassVec3f =
      nb::class_<pacer::Vec3f>(m, "Vec3f", "")
          .def_rw("x", &pacer::Vec3f::x, "")
          .def_rw("y", &pacer::Vec3f::y, "")
          .def_rw("z", &pacer::Vec3f::z, "")
          .def(nb::init<>())
          .def(nb::init<double, double, double>(), nb::arg("x"), nb::arg("y"),
               nb::arg("z"))
          .def("__getitem__",
               nb::overload_cast<size_t>(&pacer::Vec3f::operator[]),
               nb::arg("index"))
          .def("__getitem__",
               nb::overload_cast<size_t>(&pacer::Vec3f::operator[], nb::const_),
               nb::arg("index"));
  ////////////////////    </generated_from:datatypes.hpp> ////////////////////

  ////////////////////    <generated_from:geometry.hpp>    ////////////////////
  auto pyClassPoint =
      nb::class_<pacer::Point>(m, "Point", "")
          .def_rw("x", &pacer::Point::x, "")
          .def_rw("y", &pacer::Point::y, "")
          .def(nb::init<>())
          .def(nb::init<double, double>(), nb::arg("x"), nb::arg("y"))
          .def("__getitem__",
               nb::overload_cast<size_t>(&pacer::Point::operator[], nb::const_),
               nb::arg("index"))
          .def("__getitem__",
               nb::overload_cast<size_t>(&pacer::Point::operator[]),
               nb::arg("index"))
          .def("rot", &pacer::Point::Rot);

  m.def("to_point", nb::overload_cast<pacer::Point>(pacer::ToPoint),
        nb::arg("x"));

  m.def("to_point", nb::overload_cast<GPSSample>(pacer::ToPoint), nb::arg("s"));

  m.def("to_point", nb::overload_cast<Vec3f>(pacer::ToPoint), nb::arg("v"));

  auto pyClassSegment =
      nb::class_<pacer::Segment>(m, "Segment", "")
          .def(
              "__init__",
              [](pacer::Segment *self, pacer::Point first,
                 pacer::Point second) {
                new (self) pacer::Segment(); // placement new
                auto r_ctor_ = self;
                r_ctor_->first = first;
                r_ctor_->second = second;
              },
              nb::arg("first"), nb::arg("second"))
          .def_rw("first", &pacer::Segment::first, "")
          .def_rw("second", &pacer::Segment::second, "")
          .def("intersects", &pacer::Segment::Intersects, nb::arg("fst"),
               nb::arg("snd"), nb::arg("ratio"),
               " Returns True if segments intersects, if ratio is non-null, it "
               "will satisfy:\n   fst * (1 - ratio) + snd  lies  on present "
               "segment.")
          .def("__eq__", &pacer::Segment::operator==, nb::arg("other"));

  auto pyClassCoordinateSystem =
      nb::class_<pacer::CoordinateSystem>(m, "CoordinateSystem", "")
          .def(nb::init<>())
          .def(nb::init<GPSSample>(), nb::arg("origin"))
          .def("local", &pacer::CoordinateSystem::Local, nb::arg("point"),
               "/ Converts point to local coordinate system.")
          .def("global_", &pacer::CoordinateSystem::Global, nb::arg("point"),
               "/ Maps local-coordinate point back to gps sample.\n/ N.B. "
               "Speed is not preserved.")
          .def("distance", &pacer::CoordinateSystem::Distance, nb::arg("from_"),
               nb::arg("to"));

  m.def(
      "interpolate",
      nb::overload_cast<pacer::Point, pacer::Point, double>(pacer::Interpolate),
      nb::arg("from_"), nb::arg("to"), nb::arg("ratio"));

  m.def("interpolate",
        nb::overload_cast<GPSSample, GPSSample, double>(pacer::Interpolate),
        nb::arg("from_"), nb::arg("to"), nb::arg("ratio"));

  m.def("split", pacer::Split, nb::arg("start_line"), nb::arg("first"),
        nb::arg("second"));
  ////////////////////    </generated_from:geometry.hpp>    ////////////////////

  ////////////////////    <generated_from:laps.hpp>    ////////////////////
  auto pyClassLap =
      nb::class_<pacer::Lap>(m, "Lap", "")
          .def(
              "__init__",
              [](pacer::Lap *self,
                 std::vector<GPSSample> points = std::vector<GPSSample>(),
                 std::vector<double> cum_distances = std::vector<double>()) {
                new (self) pacer::Lap(); // placement new
                auto r_ctor_ = self;
                r_ctor_->points = points;
                r_ctor_->cum_distances = cum_distances;
              },
              nb::arg("points") = std::vector<GPSSample>(),
              nb::arg("cum_distances") = std::vector<double>())
          .def_rw("points", &pacer::Lap::points, "")
          .def_rw("cum_distances", &pacer::Lap::cum_distances, "")
          .def("fill_distances", &pacer::Lap::FillDistances, nb::arg("cs"))
          .def("lap_time", &pacer::Lap::LapTime)
          .def("count", &pacer::Lap::Count);

  auto pyClassSectors =
      nb::class_<pacer::Sectors>(m, "Sectors", "")
          .def(
              "__init__",
              [](pacer::Sectors *self, Segment start_line = Segment(),
                 std::vector<Segment> sector_lines = std::vector<Segment>()) {
                new (self) pacer::Sectors(); // placement new
                auto r_ctor_ = self;
                r_ctor_->start_line = start_line;
                r_ctor_->sector_lines = sector_lines;
              },
              nb::arg("start_line") = Segment(),
              nb::arg("sector_lines") = std::vector<Segment>())
          .def_rw("start_line", &pacer::Sectors::start_line, "")
          .def_rw("sector_lines", &pacer::Sectors::sector_lines, "");

  auto pyClassLaps =
      nb::class_<pacer::Laps>(m, "Laps", "")
          .def(
              "__init__",
              [](pacer::Laps *self, pacer::Sectors sectors) {
                new (self) pacer::Laps(); // placement new
                auto r_ctor_ = self;
                r_ctor_->sectors = sectors;
              },
              nb::arg("sectors"))
          .def("update", &pacer::Laps::Update,
               "/ Updates all laps given updated start_line and sector_lines")
          .def("pick_random_start", &pacer::Laps::PickRandomStart,
               "/ Picks a starting point for start_line.\n/ Default "
               "implementation builds segment perpendicular to median segment.")
          .def("set_coordinate_system", &pacer::Laps::SetCoordinateSystem,
               nb::arg("coordinate_system"))
          .def("min_max", &pacer::Laps::MinMax,
               "/ Gets bounding box for entire thing, might be cached\n/ as "
               "depends on points only.")
          .def_rw("sectors", &pacer::Laps::sectors, "")
          .def("laps_count", &pacer::Laps::LapsCount)
          .def("lap_entry_speed", &pacer::Laps::LapEntrySpeed, nb::arg("lap"))
          .def("lap_time", &pacer::Laps::LapTime, nb::arg("lap"))
          .def("sample_count", &pacer::Laps::SampleCount, nb::arg("lap"))
          .def("start_timestamp", &pacer::Laps::StartTimestamp, nb::arg("lap"))
          .def("at", &pacer::Laps::At, nb::arg("lap"), nb::arg("row"))
          .def("speed", &pacer::Laps::Speed, nb::arg("lap"), nb::arg("row"))
          .def("distance", &pacer::Laps::Distance, nb::arg("lap"),
               nb::arg("row"))
          .def("get_lap_distance", &pacer::Laps::GetLapDistance,
               nb::arg("index"), nb::arg("cs"))
          .def("get_lap", &pacer::Laps::GetLap, nb::arg("lap"))
          .def("sector_count", &pacer::Laps::SectorCount)
          .def("recorded_sectors", &pacer::Laps::RecordedSectors)
          .def("clear_sectors", &pacer::Laps::ClearSectors)
          .def("sector_time", &pacer::Laps::SectorTime, nb::arg("sector"))
          .def("sector_start_timestamp", &pacer::Laps::SectorStartTimestamp,
               nb::arg("sector"))
          .def("sector_entry_speed", &pacer::Laps::SectorEntrySpeed,
               nb::arg("sector"))
          .def("add_point", &pacer::Laps::AddPoint, nb::arg("s"))
          .def("point_count", &pacer::Laps::PointCount)
          .def("get_point", &pacer::Laps::GetPoint, nb::arg("row"))
          .def("clear_points", &pacer::Laps::ClearPoints);
  ////////////////////    </generated_from:laps.hpp>    ////////////////////

  ////////////////////    <generated_from:reference-track.hpp>
  ///////////////////////
  auto pyClassReferenceTrack =
      nb::class_<pacer::ReferenceTrack>(
          m, "ReferenceTrack",
          " A hand-annotated (or synthesized) sequence of timing-line gates "
          "used to\n project driven laps onto a common set of cross-sections "
          "for delta\n calculation. Geometry is stored in local coordinates "
          "relative to `cs`, so\n it stays internally consistent regardless of "
          "any other CoordinateSystem in\n use elsewhere (e.g. for map "
          "display).")
          .def(
              "__init__",
              [](pacer::ReferenceTrack *self,
                 CoordinateSystem cs = CoordinateSystem(),
                 std::vector<Segment> segments = std::vector<Segment>(),
                 std::vector<int> sector_indices = std::vector<int>()) {
                new (self) pacer::ReferenceTrack(); // placement new
                auto r_ctor_ = self;
                r_ctor_->cs = cs;
                r_ctor_->segments = segments;
                r_ctor_->sector_indices = sector_indices;
              },
              nb::arg("cs") = CoordinateSystem(),
              nb::arg("segments") = std::vector<Segment>(),
              nb::arg("sector_indices") = std::vector<int>())
          .def_rw("cs", &pacer::ReferenceTrack::cs, "")
          .def_rw("segments", &pacer::ReferenceTrack::segments, "")
          .def_rw("sector_indices", &pacer::ReferenceTrack::sector_indices,
                  "ordered indices into segments")
          .def("count", &pacer::ReferenceTrack::Count)
          .def("timing_lines_count", &pacer::ReferenceTrack::TimingLinesCount)
          .def("timing_line", &pacer::ReferenceTrack::TimingLine,
               nb::arg("index"),
               "/ Returns segments[index] extended a couple of meters past "
               "each edge, so\n/ the gate still catches a driven lap that "
               "strays slightly outside the\n/ annotated track boundary.")
          .def(
              "densified_gates", &pacer::ReferenceTrack::DensifiedGates,
              "/ All TimingLine()s densified to roughly one synthetic gate per "
              "meter\n/ (linearly interpolated between each annotated pair), "
              "in this track's\n/ local frame. Gate 0 is the start/finish "
              "line. Both Resample() and the\n/ live-timing engine consume "
              "laps through this same gate sequence, so\n/ their deltas agree.")
          .def("to_global", &pacer::ReferenceTrack::ToGlobal, nb::arg("local"),
               "/ Converts a local-frame segment to raw lon/lat Points, i.e. "
               "the frame\n/ pacer::Split() expects when intersecting against "
               "raw GPSSample points.")
          .def("resample", &pacer::ReferenceTrack::Resample, nb::arg("lap"),
               "/ Projects `lap` onto this track's timing lines, producing a "
               "Lap whose\n/ points align (index-for-index) with any other lap "
               "resampled against the\n/ same ReferenceTrack. Internally, "
               "consecutive gates are densified to\n/ roughly one synthetic "
               "gate per meter (linearly interpolated between\n/ each pair) so "
               "widely-spaced hand-drawn gates, e.g. down a straight,\n/ don't "
               "produce a jittery delta.")
          .def_static("from_lap", &pacer::ReferenceTrack::FromLap,
                      nb::arg("lap"), nb::arg("width"), nb::arg("cs"),
                      "/ Builds a ReferenceTrack the old way: a perpendicular "
                      "offset of `width`\n/ meters at every interior point of "
                      "`lap`. Useful when there is no\n/ hand-annotated track, "
                      "only a recorded lap to use as a stand-in.")
          .def_static(
              "from_file", &pacer::ReferenceTrack::FromFile,
              nb::arg("filename"),
              "/ Loads a reference track from the JSON schema written by\n/ "
              "track_annotator ({\"segments\": [[[lat,lon],[lat,lon]], "
              "...]}).\n/ Throws std::runtime_error on failure.")
          .def("save_to_file", &pacer::ReferenceTrack::SaveToFile,
               nb::arg("filename"),
               "/ Writes this track using the same JSON schema. Throws\n/ "
               "std::runtime_error on failure.")
          .def(
              "build_sectors", &pacer::ReferenceTrack::BuildSectors,
              nb::arg("target_cs"),
              "/ Builds a pacer::Sectors using segments[0] as the start/finish "
              "line and\n/ sector_indices (in order) as sector splits, "
              "converting from this\n/ track's local frame into target_cs (the "
              "frame the consuming Laps\n/ object uses). Returns a default "
              "(empty) Sectors if segments is empty.\n/ Uses the raw annotated "
              "segments, not the TimingLine-extended ones —\n/ the gate "
              "extension is a delta-calculation robustness hack, not\n/ "
              "something that should silently move where a lap/sector splits.");
  ////////////////////    </generated_from:reference-track.hpp>
  ///////////////////////

  ////////////////////    <generated_from:gps-source.hpp> ////////////////////
  auto pyClassRawGPSSource =
      nb::class_<pacer::RawGPSSource, pacer::RawGPSSource_trampoline>(
          m, "RawGPSSource",
          " Base class for raw GPS source.\n\n Being raw in this context means "
          "that it does not provide any meaningful\n timestamps to work with.")
          .def(nb::init<>())
          .def("read_samples", &pacer::RawGPSSource::ReadSamples,
               nb::arg("on_sample"))
          .def("seek", &pacer::RawGPSSource::Seek, nb::arg("target"),
               "Seeks to data chunk covering target.")
          .def("next", &pacer::RawGPSSource::Next,
               "Proceeds to next piece of data.")
          .def("is_end", &pacer::RawGPSSource::IsEnd,
               "Checks whenever we already reachend end of the stream.")
          .def("current_time_span", &pacer::RawGPSSource::CurrentTimeSpan,
               "Returns current samples' time span.")
          .def("get_total_duration", &pacer::RawGPSSource::GetTotalDuration,
               "Gets total MP4 duration.");

  auto pyClassGPMFSource =
      nb::class_<pacer::GPMFSource, pacer::RawGPSSource>(
          m, "GPMFSource",
          " Handler for GPMF track inside MP4 container.\n\n Allows for "
          "traversing media file and getting GPS data out of it.\n\n TODO: "
          "Provide even more low-level access to underlying samples,\n       "
          "might be useful to keep buffer for data in some sort of iterator\n  "
          "     with option to iterate over GPSSample-s on top of it.")
          .def(nb::init<size_t>(), nb::arg("mp4handle"))
          .def(nb::init<const char *>(), nb::arg("filename"))
          .def("seek", &pacer::GPMFSource::Seek, nb::arg("target"),
               "Seeks to data chunk covering target.")
          .def("next", &pacer::GPMFSource::Next,
               "Proceeds to next piece of data.")
          .def("is_end", &pacer::GPMFSource::IsEnd,
               "Checks whenever we already reachend end of the stream.")
          .def("current_time_span", &pacer::GPMFSource::CurrentTimeSpan,
               "Returns current samples' time span.")
          .def("get_total_duration", &pacer::GPMFSource::GetTotalDuration,
               "Gets total MP4 duration.");

  auto pyClassSequentialGPSSource =
      nb::class_<pacer::SequentialGPSSource, pacer::RawGPSSource>(
          m, "SequentialGPSSource", "")
          .def(nb::init<pacer::RawGPSSource *, pacer::RawGPSSource *>(),
               nb::arg("left"), nb::arg("right"))
          .def("get_total_duration",
               &pacer::SequentialGPSSource::GetTotalDuration)
          .def("is_end", &pacer::SequentialGPSSource::IsEnd)
          .def("seek", &pacer::SequentialGPSSource::Seek, nb::arg("target"))
          .def("next", &pacer::SequentialGPSSource::Next)
          .def("current_time_span",
               &pacer::SequentialGPSSource::CurrentTimeSpan,
               "Returns current samples' time span.");

  auto pyEnumDatVersion =
      nb::enum_<pacer::DatVersion>(m, "DatVersion", nb::is_arithmetic(), "")
          .value("just_data", pacer::DatVersion::JUST_DATA, "")
          .value("with_timestamp", pacer::DatVersion::WITH_TIMESTAMP, "");
  ////////////////////    </generated_from:gps-source.hpp> ////////////////////

  ////////////////////    <generated_from:laps-display.hpp> ////////////////////
  m.def("to_im_plot_point", pacer::ToImPlotPoint, nb::arg("index"),
        nb::arg("data"),
        "/ ImPlot getter over a raw GPSSample array (lon/lat). Lived in\n/ "
        "pacer::geometry before; moved here so the core geometry library has "
        "no\n/ implot dependency and can be compiled for embedded targets.");

  auto pyClassLapsDisplay =
      nb::class_<pacer::LapsDisplay>(m, "LapsDisplay", "")
          .def(
              "__init__",
              [](pacer::LapsDisplay *self, int selected_lap = -1,
                 CoordinateSystem cs = CoordinateSystem()) {
                new (self) pacer::LapsDisplay(); // placement new
                auto r_ctor_ = self;
                r_ctor_->selected_lap = selected_lap;
                r_ctor_->cs = cs;
              },
              nb::arg("selected_lap") = -1, nb::arg("cs") = CoordinateSystem())
          .def_rw("laps", &pacer::LapsDisplay::laps, "")
          .def_rw("selected_lap", &pacer::LapsDisplay::selected_lap, "")
          .def_rw("cs", &pacer::LapsDisplay::cs, "")
          .def("to_im_plot_point", &pacer::LapsDisplay::ToImPlotPoint,
               nb::arg("s"))
          .def_rw("bounds", &pacer::LapsDisplay::bounds, "")
          .def("drag_timing_line", &pacer::LapsDisplay::DragTimingLine,
               nb::arg("s"), nb::arg("name"), nb::arg("drag_id"))
          .def("display_map", &pacer::LapsDisplay::DisplayMap)
          .def("display_lap_telemetry",
               &pacer::LapsDisplay::DisplayLapTelemetry)
          .def("display_table", &pacer::LapsDisplay::DisplayTable);

  auto pyClassDeltaLapsComparision =
      nb::class_<pacer::DeltaLapsComparision>(m, "DeltaLapsComparision", "")
          .def(
              "__init__",
              [](pacer::DeltaLapsComparision *self,
                 ReferenceTrack reference_track = ReferenceTrack(),
                 CoordinateSystem cs = CoordinateSystem(),
                 std::string reference_track_filename = "track_annotation.json",
                 std::string reference_track_status = std::string(),
                 std::unordered_set<int> selected_laps = {}) {
                new (self) pacer::DeltaLapsComparision(); // placement new
                auto r_ctor_ = self;
                r_ctor_->reference_track = reference_track;
                r_ctor_->cs = cs;
                r_ctor_->reference_track_filename = reference_track_filename;
                r_ctor_->reference_track_status = reference_track_status;
                r_ctor_->selected_laps = selected_laps;
              },
              nb::arg("reference_track") = ReferenceTrack(),
              nb::arg("cs") = CoordinateSystem(),
              nb::arg("reference_track_filename") = "track_annotation.json",
              nb::arg("reference_track_status") = std::string(),
              nb::arg("selected_laps") = std::unordered_set<int>{})
          .def_rw("reference_track",
                  &pacer::DeltaLapsComparision::reference_track, "")
          .def_rw("cs", &pacer::DeltaLapsComparision::cs, "")
          .def_rw("reference_track_filename",
                  &pacer::DeltaLapsComparision::reference_track_filename, "")
          .def_rw("reference_track_status",
                  &pacer::DeltaLapsComparision::reference_track_status, "")
          .def("plot_sticks", &pacer::DeltaLapsComparision::PlotSticks)
          .def("draw_reference_track_loader",
               &pacer::DeltaLapsComparision::DrawReferenceTrackLoader,
               nb::arg("laps"))
          .def_rw("selected_laps", &pacer::DeltaLapsComparision::selected_laps,
                  "{19, 24, 28, 35, 36};")
          .def("display", &pacer::DeltaLapsComparision::Display,
               nb::arg("laps"));
  ////////////////////    </generated_from:laps-display.hpp>
  ///////////////////////

  // </litgen_pydef> // Autogenerated code end
  // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END
  // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  pyClassGPSSample.def("__repr__", [](const pacer::GPSSample &s) {
    return "GPSSample(lat=" + std::to_string(s.lat) +
           ", lon=" + std::to_string(s.lon) +
           ", altitude=" + std::to_string(s.altitude) +
           ", full_speed=" + std::to_string(s.full_speed) +
           ", ground_speed=" + std::to_string(s.ground_speed) +
           ", timestamp_ms=" + std::to_string(s.timestamp_ms) + ")";
  });

  pyClassPoint.def("__repr__", [](const pacer::Point &p) {
    return "Point(x=" + std::to_string(p.x) + ", y=" + std::to_string(p.y) +
           ")";
  });

  pyClassVec3f.def("__repr__", [](const pacer::Vec3f &v) {
    return "Vec3f(x=" + std::to_string(v.x) + ", y=" + std::to_string(v.y) +
           ", z=" + std::to_string(v.z) + ")";
  });

  pyClassSegment.def("__repr__", [](const pacer::Segment &s) {
    return "Segment(first=(" + std::to_string(s.first.x) + ", " +
           std::to_string(s.first.y) + "), second=(" +
           std::to_string(s.second.x) + ", " + std::to_string(s.second.y) +
           "))";
  });
}
