from typing import overload, Callable, Tuple, List, Any

# // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# // <litgen_stub>  // Autogenerated code below! Do not edit!
####################    <generated_from:datatypes.hpp>    ####################

class GPSSample:
    lat: float
    lon: float
    altitude: float = 0
    full_speed: float = 0
    ground_speed: float = 0
    timestamp_ms: int = 0
    def __init__(
        self,
        lat: float = float(),
        lon: float = float(),
        altitude: float = 0,
        full_speed: float = 0,
        ground_speed: float = 0,
        timestamp_ms: int = 0,
    ) -> None:
        """Auto-generated default constructor with named params"""
        pass

class Vec3f:
    x: float = 0
    y: float = 0
    z: float = 0

    @overload
    def __init__(self) -> None:
        pass

    @overload
    def __init__(self, x: float, y: float, z: float) -> None:
        pass

    @overload
    def __getitem__(self, index: int) -> float:
        pass

    @overload
    def __getitem__(self, index: int) -> float:
        pass

####################    </generated_from:datatypes.hpp>    ####################

####################    <generated_from:geometry.hpp>    ####################

class Point:
    x: float = 0
    y: float = 0

    @overload
    def __init__(self) -> None:
        pass

    @overload
    def __init__(self, x: float, y: float) -> None:
        pass

    @overload
    def __getitem__(self, index: int) -> float:
        pass

    @overload
    def __getitem__(self, index: int) -> float:
        pass

    def rot(self) -> Point:
        pass

@overload
def to_point(x: Point) -> Point:
    pass

@overload
def to_point(s: GPSSample) -> Point:
    pass

@overload
def to_point(v: Vec3f) -> Point:
    pass

# template <typename Concrete, typename T, size_t N>
# Point ToPoint(const LinearOperators<Concrete, T, N> &x) {
#   return Point{static_cast<const Concrete &>(x)[0],
#                static_cast<const Concrete &>(x)[1]};
# }

class Segment:
    first: Point
    second: Point

    def intersects(self, fst: Point, snd: Point, ratio: float) -> bool:
        """Returns True if segments intersects, if ratio is non-null, it will satisfy:
        fst * (1 - ratio) + snd  lies  on present segment.
        """
        pass

    def __eq__(self, other: Segment) -> bool:
        pass

    def __init__(self, first: Point = Point(), second: Point = Point()) -> None:
        """Auto-generated default constructor with named params"""
        pass

class CoordinateSystem:
    # Coordinate system maps GPS coordinates to local coordinates.
    #  N.B. All local coordinates measured in meters.
    #
    # I employ following formulas:
    #   x = h_c * R_equator * cos(lat) * cos(lon)
    #   y = h_c * R_equator * cos(lat) * sin(lon)
    #   z = h_c * R_pole * sin(lat)
    #
    # Where h_c is the height compenstaion factor:
    #   h_c = 1 + altitude / R_equator
    #
    # Basis for resulting coordinate system is almost normalised gradients along
    # lon/lat/altiude coordinates: only altitude slightly differs to have
    # ortogonal system:
    #  dx = (-R_equator cos(lat) sin(lon), R_equator cos(lat) cos(lon), 0)
    #  dy = (-R_equator sin(lat) cos(lon), -R_equator sin(lat) sin(lon),
    #        R_pole cos(lat))
    #  dz = (R_pole cos(lat) cos(lon), R_pole cos(lat) sin(lon),
    #        R_equator sin(lat))
    #
    # This is most likely not the best way to do this, but it works for now.

    @overload
    def __init__(self) -> None:
        pass

    @overload
    def __init__(self, origin: GPSSample) -> None:
        pass

    def local(self, point: GPSSample) -> Vec3f:
        """/ Converts point to local coordinate system."""
        pass

    def global_(self, point: Vec3f) -> GPSSample:
        """/ Maps local-coordinate point back to gps sample.
        / N.B. Speed is not preserved.
        """
        pass

    def distance(self, from_: GPSSample, to: GPSSample) -> float:
        pass

@overload
def interpolate(from_: Point, to: Point, ratio: float) -> Point:
    pass

@overload
def interpolate(from_: GPSSample, to: GPSSample, ratio: float) -> GPSSample:
    pass

# template <typename Concrete, typename T, size_t N>
# Concrete Interpolate(const LinearOperators<Concrete, T, N> &from,
#                      const LinearOperators<Concrete, T, N> &to, double ratio)
#                      {
#   return static_cast<Concrete>(static_cast<const Concrete &>(from) *
#                                    (1 - ratio) +
#                                static_cast<const Concrete &>(to) * ratio);
# }

def split(
    start_line: Segment, first: GPSSample, second: GPSSample
) -> Optional[GPSSample]:
    pass

####################    </generated_from:geometry.hpp>    ####################

####################    <generated_from:laps.hpp>    ####################

class Lap:
    points: List[GPSSample]

    cum_distances: List[float]

    def fill_distances(self, cs: CoordinateSystem) -> None:
        pass

    def lap_time(self) -> float:
        pass

    def count(self) -> int:
        pass

    def __init__(
        self,
        points: List[GPSSample] = List[GPSSample](),
        cum_distances: List[float] = List[float](),
    ) -> None:
        """Auto-generated default constructor with named params"""
        pass

class Sectors:
    start_line: Segment

    sector_lines: List[Segment]
    def __init__(
        self,
        start_line: Segment = Segment(),
        sector_lines: List[Segment] = List[Segment](),
    ) -> None:
        """Auto-generated default constructor with named params"""
        pass

class Laps:
    def update(self) -> None:
        """/ Updates all laps given updated start_line and sector_lines"""
        pass

    def pick_random_start(self) -> Segment:
        """/ Picks a starting point for start_line.
        / Default implementation builds segment perpendicular to median segment.
        """
        pass
    # ---------------------------- PRESENTATION -------------------------------//

    def set_coordinate_system(self, coordinate_system: CoordinateSystem) -> None:
        pass

    def min_max(self) -> Tuple[Point, Point]:
        """/ Gets bounding box for entire thing, might be cached
        / as depends on points only.
        """
        pass
    # -------------------------------- LAPS -----------------------------------//

    sectors: Sectors

    def laps_count(self) -> int:
        pass

    def lap_entry_speed(self, lap: int) -> float:
        pass

    def lap_time(self, lap: int) -> float:
        pass

    def sample_count(self, lap: int) -> int:
        pass

    def start_timestamp(self, lap: int) -> float:
        pass

    def at(self, lap: int, row: int) -> GPSSample:
        pass

    def speed(self, lap: int, row: int) -> float:
        pass

    def distance(self, lap: int, row: int) -> float:
        pass

    def get_lap_distance(self, index: int, cs: CoordinateSystem) -> float:
        pass

    def get_lap(self, lap: int) -> Lap:
        pass
    # ------------------------------- SECTORS ---------------------------------//

    def sector_count(self) -> int:
        pass

    def recorded_sectors(self) -> int:
        pass

    def clear_sectors(self) -> None:
        pass

    def sector_time(self, sector: int) -> float:
        pass

    def sector_start_timestamp(self, sector: int) -> float:
        pass

    def sector_entry_speed(self, sector: int) -> float:
        pass
    # ------------------------------ RAW POINTS -------------------------------//

    def add_point(self, s: GPSSample) -> None:
        pass

    def point_count(self) -> int:
        pass

    def get_point(self, row: int) -> GPSSample:
        pass

    def clear_points(self) -> None:
        pass

    def __init__(self, sectors: Sectors = Sectors()) -> None:
        """Auto-generated default constructor with named params"""
        pass

####################    </generated_from:laps.hpp>    ####################

####################    <generated_from:reference-track.hpp>    ####################

class ReferenceTrack:
    """A hand-annotated (or synthesized) sequence of timing-line gates used to
    project driven laps onto a common set of cross-sections for delta
    calculation. Geometry is stored in local coordinates relative to `cs`, so
    it stays internally consistent regardless of any other CoordinateSystem in
    use elsewhere (e.g. for map display).
    """

    cs: CoordinateSystem
    segments: List[Segment]
    sector_indices: List[int]  # ordered indices into segments

    # / How far TimingLine() extends each gate past both annotated edges, in
    # / meters, so the gate still catches a driven lap that strays slightly
    # / outside the annotated track boundary. Runtime-only (not saved to the
    # / track file); tune it in the timeline's reference track loader.
    gate_extension_m: float = 2.0

    def count(self) -> int:
        pass

    def timing_lines_count(self) -> int:
        pass

    def timing_line(self, index: int) -> Segment:
        """/ Returns segments[index] extended gate_extension_m past each edge."""
        pass

    def densified_gates(self) -> List[Segment]:
        """/ All TimingLine()s densified to roughly one synthetic gate per meter
        / (linearly interpolated between each annotated pair), in this track's
        / local frame. Gate 0 is the start/finish line. Both Resample() and the
        / live-timing engine consume laps through this same gate sequence, so
        / their deltas agree.
        """
        pass

    def to_global(self, local: Segment) -> Segment:
        """/ Converts a local-frame segment to raw lon/lat Points, i.e. the frame
        / pacer::Split() expects when intersecting against raw GPSSample points.
        """
        pass

    def resample(self, lap: Lap) -> Lap:
        """/ Projects `lap` onto this track's timing lines, producing a Lap whose
        / points align (index-for-index) with any other lap resampled against the
        / same ReferenceTrack. Internally, consecutive gates are densified to
        / roughly one synthetic gate per meter (linearly interpolated between
        / each pair) so widely-spaced hand-drawn gates, e.g. down a straight,
        / don't produce a jittery delta.
        """
        pass

    @staticmethod
    def from_lap(lap: Lap, width: float, cs: CoordinateSystem) -> ReferenceTrack:
        """/ Builds a ReferenceTrack the old way: a perpendicular offset of `width`
        / meters at every interior point of `lap`. Useful when there is no
        / hand-annotated track, only a recorded lap to use as a stand-in.
        """
        pass

    @staticmethod
    def from_file(filename: str) -> ReferenceTrack:
        """/ Loads a reference track from the JSON schema written by
        / track_annotator ({"segments": [[[lat,lon],[lat,lon]], ...]}).
        / Throws std::runtime_error on failure.
        """
        pass

    def save_to_file(self, filename: str) -> None:
        """/ Writes this track using the same JSON schema. Throws
        / std::runtime_error on failure.
        """
        pass

    def build_sectors(self, target_cs: CoordinateSystem) -> Sectors:
        """/ Builds a pacer::Sectors using segments[0] as the start/finish line and
        / sector_indices (in order) as sector splits, converting from this
        / track's local frame into target_cs (the frame the consuming Laps
        / object uses). Returns a default (empty) Sectors if segments is empty.
        / Lines are TimingLine-extended by gate_extension_m, same as the delta
        / gates, so laps running slightly wide of the annotated track edges
        / still register lap/sector splits.
        """
        pass

    def __init__(
        self,
        cs: CoordinateSystem = CoordinateSystem(),
        segments: List[Segment] = List[Segment](),
        sector_indices: List[int] = List[int](),
        gate_extension_m: float = 2.0,
    ) -> None:
        """Auto-generated default constructor with named params"""
        pass

####################    </generated_from:reference-track.hpp>    ####################

####################    <generated_from:gps-source.hpp>    ####################

class RawGPSSource:
    """Base class for raw GPS source.

    Being raw in this context means that it does not provide any meaningful
    timestamps to work with.
    """

    def __init__(self) -> None:
        pass

    def read_samples(self, on_sample: Callable[[GPSSample, int, int], None]) -> int:
        pass

    def seek(self, target: float) -> int:  # overridable (pure virtual)
        """Seeks to data chunk covering target."""
        pass

    def next(self) -> None:  # overridable (pure virtual)
        """Proceeds to next piece of data."""
        pass

    def is_end(self) -> bool:  # overridable (pure virtual)
        """Checks whenever we already reachend end of the stream."""
        pass

    def current_time_span(self) -> Tuple[float, float]:  # overridable (pure virtual)
        """Returns current samples' time span."""
        pass

    def get_total_duration(self) -> float:  # overridable (pure virtual)
        """Gets total MP4 duration."""
        pass

class GPMFSource(RawGPSSource):
    """Handler for GPMF track inside MP4 container.

    Allows for traversing media file and getting GPS data out of it.

    TODO: Provide even more low-level access to underlying samples,
          might be useful to keep buffer for data in some sort of iterator
          with option to iterate over GPSSample-s on top of it.
    """

    @overload
    def __init__(self, mp4handle: int) -> None:
        pass

    @overload
    def __init__(self, filename: str) -> None:
        pass

    def seek(self, target: float) -> int:
        """Seeks to data chunk covering target."""
        pass

    def next(self) -> None:
        """Proceeds to next piece of data."""
        pass

    def is_end(self) -> bool:
        """Checks whenever we already reachend end of the stream."""
        pass

    def current_time_span(self) -> Tuple[float, float]:
        """Returns current samples' time span."""
        pass

    def get_total_duration(self) -> float:
        """Gets total MP4 duration."""
        pass

class SequentialGPSSource(RawGPSSource):
    def __init__(self, left: RawGPSSource, right: RawGPSSource) -> None:
        pass

    def get_total_duration(self) -> float:
        pass

    def is_end(self) -> bool:
        pass

    def seek(self, target: float) -> int:
        pass

    def next(self) -> None:
        pass

    def current_time_span(self) -> Tuple[float, float]:
        """Returns current samples' time span."""
        pass

class DatVersion(enum.IntEnum):
    just_data = enum.auto()  # (= 0)
    with_timestamp = enum.auto()  # (= 1)

def load_gps_files(
    filenames: List[str],
    on_sample: Callable[[GPSSample], None],
    errors: Optional[List[str]] = None,
) -> int:
    """/ Loads GPS samples from a mix of .dat and GPMF (.mp4 etc.) files, in the
    / given order. Samples that predate embedded timestamps get a clock
    / synthesized from the MP4 chunk spans, chained across files so they stay
    / ordered. Missing/unreadable files are reported through `errors` (if
    / non-null). Returns the number of files samples were loaded from.
    """
    pass

####################    </generated_from:gps-source.hpp>    ####################

####################    <generated_from:laps-display.hpp>    ####################

def to_im_plot_point(index: int, data: Any) -> ImPlotPoint:
    """/ ImPlot getter over a raw GPSSample array (lon/lat). Lived in
    / pacer::geometry before; moved here so the core geometry library has no
    / implot dependency and can be compiled for embedded targets.
    """
    pass

class LapsDisplay:
    laps: Laps
    selected_lap: int = -1

    cs: CoordinateSystem

    # / True once a frame was supplied via SetMapFrame (e.g. by a reference
    # / track); SetupMap then keeps that frame instead of deriving one from
    # / the loaded points.
    has_supplied_frame: bool = False

    def to_im_plot_point(self, s: GPSSample) -> ImPlotPoint:
        pass
    bounds: Tuple[Point, Point] = Tuple[Point, Point]({1, 1}, {0, 0})

    def has_map_frame(self) -> bool:
        """/ True once cs maps plot coordinates to real lat/lon — either supplied
        / via SetMapFrame or derived from loaded points by SetupMap.
        """
        pass

    def set_map_frame(self, frame: CoordinateSystem) -> None:
        """/ Adopts `frame` as the map coordinate system (typically the reference
        / track's cs, so sectors/delta/display all share one frame that outlives
        / any particular set of loaded data files). Propagates it to the laps and
        / schedules an axis refit on the next SetupMap.
        """
        pass

    def setup_map(self) -> None:
        """/ Initializes cs/bounds from the loaded points and fits the plot axes.
        / If a frame was supplied via SetMapFrame, only the bounds/axes are
        / refit; the supplied frame is kept.
        / Call right after ImPlot::BeginPlot, before plotting any item.
        """
        pass

    def plot_map_items(self) -> None:
        """/ Plots the GPS trace plus the start/sector timing lines (read-only;
        / edit the geometry in track_annotator).
        """
        pass

    def display_lap_telemetry(self) -> None:
        pass

    def display_table(self) -> bool:
        pass

    def __init__(
        self,
        selected_lap: int = -1,
        cs: CoordinateSystem = CoordinateSystem(),
        has_supplied_frame: bool = False,
    ) -> None:
        """Auto-generated default constructor with named params"""
        pass

class DeltaLapsComparision:
    reference_track: ReferenceTrack
    cs: CoordinateSystem

    reference_track_status: str

    # / UI-owned copy of ReferenceTrack::gate_extension_m; survives reloads
    # / (FromFile resets the track to the default) and is re-applied to the
    # / loaded track every frame by DrawReferenceTrackLoader.
    gate_extension_m: float = 2.0

    def plot_sticks(self) -> None:
        pass

    def draw_reference_track_loader(self, laps: Laps, display: LapsDisplay) -> None:
        """/ Draws the picker/load UI. On a successful load the reference track's
        / own coordinate system becomes the map frame: it is pushed into
        / `display` (and from there into `laps`), adopted as this->cs, and the
        / sectors are built directly in it.
        """
        pass
    selected_laps: std.unordered_set[int] = std.unordered_set < int > ()

    @staticmethod
    def lap_color(lap_id: int) -> ImVec4:
        """/ Stable per-lap color used by the speed trace, delta plot and the
        / comparison map, so a lap is recognizable across all three views.
        """
        pass

    def display(self, laps: Laps) -> None:
        pass
    # --------------------------- COMPARISON MAP -----------------------------//
    # The map itself is plotted by the app (it owns the TileStore; the
    # map-tiles library is desktop-only) as:
    #   BeginPlot -> SetupComparisonMap -> [PlotSatelliteTiles]
    #     -> PlotComparisonMap -> EndPlot

    show_satellite: bool = True
    show_reference_track: bool = True

    def setup_comparison_map(self) -> None:
        """/ Fits the plot axes to the reference track once per track load.
        / Call right after ImPlot::BeginPlot.
        """
        pass

    def plot_comparison_map(self, laps: Laps) -> None:
        """/ Plots the reference track gates and the selected laps' trajectories
        / (in this->cs local meters), plus the hover markers. Hovering the plot
        / inside the track bounds projects the mouse onto the track middle line
        / and shares the resulting distance with the speed/delta plots.
        """
        pass
    # ------------------------------- HOVER ----------------------------------//

    def set_hover_distance(self, distance: float) -> None:
        """/ Publishes a hovered distance along the (best) lap for the current
        / frame; every view then draws its own cursor/annotations from it.
        """
        pass

    def hover_distance(self) -> Optional[float]:
        """/ Distance published this frame or the previous one (views are drawn in
        / separate windows, so a consumer may run before this frame's producer).
        """
        pass

    def __init__(
        self,
        reference_track: ReferenceTrack = ReferenceTrack(),
        cs: CoordinateSystem = CoordinateSystem(),
        reference_track_status: str = "",
        gate_extension_m: float = 2.0,
        selected_laps: std.unordered_set[int] = std.unordered_set < int > (),
        show_satellite: bool = True,
        show_reference_track: bool = True,
    ) -> None:
        """Auto-generated default constructor with named params"""
        pass

####################    </generated_from:laps-display.hpp>    ####################

# // </litgen_stub> // Autogenerated code end
# // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
